"""create_user_auth_identities_table

Revision ID: 0898a6eeb570
Revises: c8d9e0f1a2b3
Create Date: 2026-07-31 11:31:13.984717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0898a6eeb570'
down_revision: Union[str, None] = 'c8d9e0f1a2b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('binding_tickets',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ticket_hash', sa.String(length=64), nullable=False),
    sa.Column('openid', sa.String(length=200), nullable=False),
    sa.Column('unionid', sa.String(length=200), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('client_ip', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticket_hash')
    )
    op.create_index('idx_binding_openid', 'binding_tickets', ['openid'], unique=False)
    op.create_index(op.f('ix_binding_tickets_openid'), 'binding_tickets', ['openid'], unique=False)
    op.create_table('auth_sessions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=64), nullable=False),
    sa.Column('session_type', sa.String(length=30), nullable=False),
    sa.Column('client_ip', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('device_id', sa.String(length=200), nullable=True),
    sa.Column('device_info', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('last_active_at', sa.DateTime(), nullable=True),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('refresh_token_hash')
    )
    op.create_index('idx_session_expires', 'auth_sessions', ['expires_at'], unique=False)
    op.create_index('idx_session_hash', 'auth_sessions', ['refresh_token_hash'], unique=False)
    op.create_index('idx_session_user', 'auth_sessions', ['user_id'], unique=False)
    op.create_index(op.f('ix_auth_sessions_user_id'), 'auth_sessions', ['user_id'], unique=False)
    op.create_table('user_auth_identities',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('identity_type', sa.String(length=50), nullable=False, comment='身份类型: email_password / wechat_miniprogram'),
    sa.Column('identity_key', sa.String(length=500), nullable=False, comment='身份标识: 邮箱地址 / 微信 openid'),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('openid', sa.String(length=200), nullable=True),
    sa.Column('unionid', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_identity_user', 'user_auth_identities', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_auth_identities_openid'), 'user_auth_identities', ['openid'], unique=False)
    op.create_index(op.f('ix_user_auth_identities_user_id'), 'user_auth_identities', ['user_id'], unique=False)
    op.create_index('uq_identity_type_key', 'user_auth_identities', ['identity_type', 'identity_key'], unique=True)
    op.alter_column('ai_invocation_logs', 'output_status',
               existing_type=sa.VARCHAR(length=32),
               comment='输出状态：success / timeout / rate_limit / insufficient_quota / network_error / json_parse_error / circuit_breaker / error',
               existing_comment='输出状态：success/timeout/rate_limit/insufficient_quota/network_error/json_parse_error/circuit_breaker/error',
               existing_nullable=False)
    op.alter_column('ai_invocation_logs', 'fallback_reason',
               existing_type=sa.VARCHAR(length=200),
               comment='降级原因（失败时填，如 AI 超时已降级普通搜索）',
               existing_comment='降级原因（失败时填）',
               existing_nullable=True)
    op.drop_index(op.f('ix_ai_invocation_logs_id'), table_name='ai_invocation_logs')
    op.alter_column('browse_histories', 'school_id',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='学校 ID（按学校隔离浏览历史）',
               existing_nullable=False)
    op.alter_column('browse_histories', 'viewed_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='最近一次浏览时间',
               existing_nullable=False)
    op.create_index(op.f('ix_browse_histories_school_id'), 'browse_histories', ['school_id'], unique=False)
    op.alter_column('job_run_records', 'processed_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_comment='成功处理数量',
               existing_nullable=False)
    op.alter_column('job_run_records', 'failed_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_comment='失败数量',
               existing_nullable=False)
    op.alter_column('job_run_records', 'triggered_by',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_comment='触发者：system / manual / 手动触发的 user_id',
               existing_nullable=False)
    op.alter_column('job_run_records', 'dry_run',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_comment='是否为 dry-run（只报告不执行）',
               existing_nullable=False)
    op.alter_column('notification_preferences', 'user_id',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='用户 ID',
               existing_nullable=False)
    op.alter_column('notification_preferences', 'instant_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_comment='站内即时通知',
               existing_nullable=False)
    op.alter_column('notification_preferences', 'subscription_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_comment='订阅类',
               existing_nullable=False)
    op.alter_column('notification_preferences', 'interaction_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_comment='互动类',
               existing_nullable=False)
    op.alter_column('notification_preferences', 'audit_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_comment='审核类（安全账号通知不可全关）',
               existing_nullable=False)
    op.alter_column('notification_preferences', 'governance_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_comment='治理类',
               existing_nullable=False)
    op.alter_column('notification_preferences', 'system_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_comment='系统类（安全账号通知不可全关）',
               existing_nullable=False)
    op.alter_column('notification_preferences', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('notification_preferences', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('idx_notification_preference_user'), table_name='notification_preferences')
    op.create_index(op.f('ix_notification_preferences_user_id'), 'notification_preferences', ['user_id'], unique=True)
    op.alter_column('password_reset_tokens', 'user_id',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='用户 ID',
               existing_nullable=False)
    op.drop_index(op.f('ix_password_reset_tokens_id'), table_name='password_reset_tokens')
    op.drop_constraint(op.f('uq_password_reset_token_hash'), 'password_reset_tokens', type_='unique')
    op.alter_column('plan_entitlements', 'key',
               existing_type=sa.VARCHAR(length=40),
               comment='权益 key：members_max/posts_max/storage_mb/ai_calls_daily 等',
               existing_nullable=False)
    op.alter_column('plan_entitlements', 'limit_value',
               existing_type=sa.INTEGER(),
               comment='额度上限；NULL 或 0 表示不限',
               existing_nullable=True)
    op.alter_column('plan_entitlements', 'is_hard',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               comment='True=硬限制（拒绝），False=软限制（告警）',
               existing_nullable=False)
    op.alter_column('plan_entitlements', 'description',
               existing_type=sa.TEXT(),
               comment='权益项说明',
               existing_nullable=True)
    op.create_index('idx_platform_audit_action', 'platform_audit_logs', ['action'], unique=False)
    op.create_index('idx_platform_audit_created', 'platform_audit_logs', ['created_at'], unique=False)
    op.alter_column('product_events', 'fields_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='最小字段集（白名单 schema 严格校验，不含正文/密码/Token/完整搜索关键词）',
               existing_comment='最小字段集（白名单 schema 严格校验）',
               existing_nullable=True)
    op.drop_constraint(op.f('uq_product_event_event_id'), 'product_events', type_='unique')
    op.alter_column('product_plans', 'code',
               existing_type=sa.VARCHAR(length=30),
               comment='套餐代码：trial/standard/operations',
               existing_nullable=False)
    op.alter_column('product_plans', 'name',
               existing_type=sa.VARCHAR(length=60),
               comment='套餐显示名',
               existing_nullable=False)
    op.alter_column('product_plans', 'description',
               existing_type=sa.TEXT(),
               comment='套餐说明',
               existing_nullable=True)
    op.alter_column('product_plans', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               comment='套餐状态：active/retired',
               existing_nullable=False)
    op.alter_column('product_plans', 'sort_order',
               existing_type=sa.INTEGER(),
               server_default=None,
               comment='展示排序，小在前',
               existing_nullable=False)
    op.alter_column('school_domains', 'is_primary',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('school_invitations', 'role',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('school_invitations', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_comment='邀请状态：expires/accepted/declined',
               existing_nullable=False)
    op.alter_column('school_memberships', 'role',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_comment='成员角色：member/admin（super_admin 仍是平台角色在 user 表）',
               existing_nullable=False)
    op.alter_column('school_memberships', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_comment='成员状态：active/invited/suspended',
               existing_nullable=False)
    op.alter_column('school_memberships', 'is_default',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('school_settings', 'require_review',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('school_settings', 'allow_anonymous',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('school_settings', 'allow_comments',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('school_settings', 'publish_frequency',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_comment='每日发布上限（0 表示不限）',
               existing_nullable=False)
    op.alter_column('school_settings', 'image_limit',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_comment='单帖图片上限',
               existing_nullable=False)
    op.alter_column('school_settings', 'default_validity_days',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('school_subscriptions', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               comment='订阅状态：active/expired/suspended',
               existing_nullable=False)
    op.alter_column('school_subscriptions', 'expires_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='到期时间；NULL 表示不限',
               existing_nullable=True)
    op.alter_column('school_subscriptions', 'assigned_by',
               existing_type=sa.BIGINT(),
               comment='分配/续期操作者 user_id',
               existing_nullable=True)
    op.alter_column('school_subscriptions', 'assigned_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='最近一次分配/续期时间',
               existing_nullable=False)
    op.alter_column('school_subscriptions', 'note',
               existing_type=sa.TEXT(),
               comment='操作备注（旧值/新值/原因）',
               existing_nullable=True)
    op.alter_column('subscriptions', 'user_id',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='订阅用户 ID',
               existing_nullable=False)
    op.alter_column('subscriptions', 'school_id',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='学校 ID（TEN-02 三校隔离）',
               existing_nullable=False)
    op.alter_column('subscriptions', 'target_id',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='订阅目标 ID（categories.id / locations.id / topic_collections.id）',
               existing_nullable=False)
    op.alter_column('subscriptions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('tenant_usage_daily', 'usage_date',
               existing_type=postgresql.TIMESTAMP(precision=0),
               type_=sa.Date(),
               comment='统计日期 YYYY-MM-DD',
               existing_nullable=False)
    op.alter_column('tenant_usage_daily', 'members_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('tenant_usage_daily', 'posts_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('tenant_usage_daily', 'storage_used_mb',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('tenant_usage_daily', 'ai_calls_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('user_recommendation_preferences', 'user_id',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='用户 ID',
               existing_nullable=False)
    op.alter_column('user_recommendation_preferences', 'personalization_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               comment='REC-01.2: 是否启用个性化推荐；关闭后改用冷启动（本校热门/最新/管理员推荐）',
               existing_comment='REC-01.2: 是否启用个性化推荐；关闭后改用冷启动',
               existing_nullable=False)
    op.alter_column('user_recommendation_preferences', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('user_recommendation_preferences', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'reputation_score',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               comment='历史字段：用户信誉分（当前主应用不再维护）',
               existing_comment='用户信誉分（0-100），由 sp_update_reputation 计算',
               existing_nullable=True)
    op.create_index('idx_validation_post_user_unique', 'validation_records', ['post_id', 'user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_validation_post_user_unique', table_name='validation_records')
    op.alter_column('users', 'reputation_score',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               comment='用户信誉分（0-100），由 sp_update_reputation 计算',
               existing_comment='历史字段：用户信誉分（当前主应用不再维护）',
               existing_nullable=True)
    op.alter_column('user_recommendation_preferences', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('user_recommendation_preferences', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('user_recommendation_preferences', 'personalization_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               comment='REC-01.2: 是否启用个性化推荐；关闭后改用冷启动',
               existing_comment='REC-01.2: 是否启用个性化推荐；关闭后改用冷启动（本校热门/最新/管理员推荐）',
               existing_nullable=False)
    op.alter_column('user_recommendation_preferences', 'user_id',
               existing_type=sa.BIGINT(),
               comment='用户 ID',
               existing_nullable=False)
    op.alter_column('tenant_usage_daily', 'ai_calls_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('tenant_usage_daily', 'storage_used_mb',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('tenant_usage_daily', 'posts_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('tenant_usage_daily', 'members_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('tenant_usage_daily', 'usage_date',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(precision=0),
               comment=None,
               existing_comment='统计日期 YYYY-MM-DD',
               existing_nullable=False)
    op.alter_column('subscriptions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('subscriptions', 'target_id',
               existing_type=sa.BIGINT(),
               comment='订阅目标 ID（categories.id / locations.id / topic_collections.id）',
               existing_nullable=False)
    op.alter_column('subscriptions', 'school_id',
               existing_type=sa.BIGINT(),
               comment='学校 ID（TEN-02 三校隔离）',
               existing_nullable=False)
    op.alter_column('subscriptions', 'user_id',
               existing_type=sa.BIGINT(),
               comment='订阅用户 ID',
               existing_nullable=False)
    op.alter_column('school_subscriptions', 'note',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='操作备注（旧值/新值/原因）',
               existing_nullable=True)
    op.alter_column('school_subscriptions', 'assigned_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='最近一次分配/续期时间',
               existing_nullable=False)
    op.alter_column('school_subscriptions', 'assigned_by',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='分配/续期操作者 user_id',
               existing_nullable=True)
    op.alter_column('school_subscriptions', 'expires_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='到期时间；NULL 表示不限',
               existing_nullable=True)
    op.alter_column('school_subscriptions', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'active'::character varying"),
               comment=None,
               existing_comment='订阅状态：active/expired/suspended',
               existing_nullable=False)
    op.alter_column('school_settings', 'default_validity_days',
               existing_type=sa.INTEGER(),
               server_default=sa.text('30'),
               existing_nullable=False)
    op.alter_column('school_settings', 'image_limit',
               existing_type=sa.INTEGER(),
               server_default=sa.text('9'),
               existing_comment='单帖图片上限',
               existing_nullable=False)
    op.alter_column('school_settings', 'publish_frequency',
               existing_type=sa.INTEGER(),
               server_default=sa.text('10'),
               existing_comment='每日发布上限（0 表示不限）',
               existing_nullable=False)
    op.alter_column('school_settings', 'allow_comments',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('school_settings', 'allow_anonymous',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('school_settings', 'require_review',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('school_memberships', 'is_default',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('school_memberships', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'active'::character varying"),
               existing_comment='成员状态：active/invited/suspended',
               existing_nullable=False)
    op.alter_column('school_memberships', 'role',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'member'::character varying"),
               existing_comment='成员角色：member/admin（super_admin 仍是平台角色在 user 表）',
               existing_nullable=False)
    op.alter_column('school_invitations', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'expires'::character varying"),
               existing_comment='邀请状态：expires/accepted/declined',
               existing_nullable=False)
    op.alter_column('school_invitations', 'role',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'member'::character varying"),
               existing_nullable=False)
    op.alter_column('school_domains', 'is_primary',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('product_plans', 'sort_order',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               comment=None,
               existing_comment='展示排序，小在前',
               existing_nullable=False)
    op.alter_column('product_plans', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'active'::character varying"),
               comment=None,
               existing_comment='套餐状态：active/retired',
               existing_nullable=False)
    op.alter_column('product_plans', 'description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='套餐说明',
               existing_nullable=True)
    op.alter_column('product_plans', 'name',
               existing_type=sa.VARCHAR(length=60),
               comment=None,
               existing_comment='套餐显示名',
               existing_nullable=False)
    op.alter_column('product_plans', 'code',
               existing_type=sa.VARCHAR(length=30),
               comment=None,
               existing_comment='套餐代码：trial/standard/operations',
               existing_nullable=False)
    op.create_unique_constraint(op.f('uq_product_event_event_id'), 'product_events', ['event_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('product_events', 'fields_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='最小字段集（白名单 schema 严格校验）',
               existing_comment='最小字段集（白名单 schema 严格校验，不含正文/密码/Token/完整搜索关键词）',
               existing_nullable=True)
    op.drop_index('idx_platform_audit_created', table_name='platform_audit_logs')
    op.drop_index('idx_platform_audit_action', table_name='platform_audit_logs')
    op.alter_column('plan_entitlements', 'description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='权益项说明',
               existing_nullable=True)
    op.alter_column('plan_entitlements', 'is_hard',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               comment=None,
               existing_comment='True=硬限制（拒绝），False=软限制（告警）',
               existing_nullable=False)
    op.alter_column('plan_entitlements', 'limit_value',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='额度上限；NULL 或 0 表示不限',
               existing_nullable=True)
    op.alter_column('plan_entitlements', 'key',
               existing_type=sa.VARCHAR(length=40),
               comment=None,
               existing_comment='权益 key：members_max/posts_max/storage_mb/ai_calls_daily 等',
               existing_nullable=False)
    op.create_unique_constraint(op.f('uq_password_reset_token_hash'), 'password_reset_tokens', ['token_hash'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_password_reset_tokens_id'), 'password_reset_tokens', ['id'], unique=False)
    op.alter_column('password_reset_tokens', 'user_id',
               existing_type=sa.BIGINT(),
               comment='用户 ID',
               existing_nullable=False)
    op.drop_index(op.f('ix_notification_preferences_user_id'), table_name='notification_preferences')
    op.create_index(op.f('idx_notification_preference_user'), 'notification_preferences', ['user_id'], unique=False)
    op.alter_column('notification_preferences', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('notification_preferences', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('notification_preferences', 'system_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_comment='系统类（安全账号通知不可全关）',
               existing_nullable=False)
    op.alter_column('notification_preferences', 'governance_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_comment='治理类',
               existing_nullable=False)
    op.alter_column('notification_preferences', 'audit_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_comment='审核类（安全账号通知不可全关）',
               existing_nullable=False)
    op.alter_column('notification_preferences', 'interaction_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_comment='互动类',
               existing_nullable=False)
    op.alter_column('notification_preferences', 'subscription_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_comment='订阅类',
               existing_nullable=False)
    op.alter_column('notification_preferences', 'instant_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_comment='站内即时通知',
               existing_nullable=False)
    op.alter_column('notification_preferences', 'user_id',
               existing_type=sa.BIGINT(),
               comment='用户 ID',
               existing_nullable=False)
    op.alter_column('job_run_records', 'dry_run',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_comment='是否为 dry-run（只报告不执行）',
               existing_nullable=False)
    op.alter_column('job_run_records', 'triggered_by',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'system'::character varying"),
               existing_comment='触发者：system / manual / 手动触发的 user_id',
               existing_nullable=False)
    op.alter_column('job_run_records', 'failed_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_comment='失败数量',
               existing_nullable=False)
    op.alter_column('job_run_records', 'processed_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_comment='成功处理数量',
               existing_nullable=False)
    op.drop_index(op.f('ix_browse_histories_school_id'), table_name='browse_histories')
    op.alter_column('browse_histories', 'viewed_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='最近一次浏览时间',
               existing_nullable=False)
    op.alter_column('browse_histories', 'school_id',
               existing_type=sa.BIGINT(),
               comment='学校 ID（按学校隔离浏览历史）',
               existing_nullable=False)
    op.create_index(op.f('ix_ai_invocation_logs_id'), 'ai_invocation_logs', ['id'], unique=False)
    op.alter_column('ai_invocation_logs', 'fallback_reason',
               existing_type=sa.VARCHAR(length=200),
               comment='降级原因（失败时填）',
               existing_comment='降级原因（失败时填，如 AI 超时已降级普通搜索）',
               existing_nullable=True)
    op.alter_column('ai_invocation_logs', 'output_status',
               existing_type=sa.VARCHAR(length=32),
               comment='输出状态：success/timeout/rate_limit/insufficient_quota/network_error/json_parse_error/circuit_breaker/error',
               existing_comment='输出状态：success / timeout / rate_limit / insufficient_quota / network_error / json_parse_error / circuit_breaker / error',
               existing_nullable=False)
    op.drop_index('uq_identity_type_key', table_name='user_auth_identities')
    op.drop_index(op.f('ix_user_auth_identities_user_id'), table_name='user_auth_identities')
    op.drop_index(op.f('ix_user_auth_identities_openid'), table_name='user_auth_identities')
    op.drop_index('idx_identity_user', table_name='user_auth_identities')
    op.drop_table('user_auth_identities')
    op.drop_index(op.f('ix_auth_sessions_user_id'), table_name='auth_sessions')
    op.drop_index('idx_session_user', table_name='auth_sessions')
    op.drop_index('idx_session_hash', table_name='auth_sessions')
    op.drop_index('idx_session_expires', table_name='auth_sessions')
    op.drop_table('auth_sessions')
    op.drop_index(op.f('ix_binding_tickets_openid'), table_name='binding_tickets')
    op.drop_index('idx_binding_openid', table_name='binding_tickets')
    op.drop_table('binding_tickets')
    # ### end Alembic commands ###
