"""openGauss initial migration

Revision ID: af3fef102173
Revises: 
Create Date: 2026-06-29 13:27:24.045709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af3fef102173'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('icon', sa.String(length=10), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('default_validity_days', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_category_code', 'categories', ['code'], unique=True)
    op.create_index('idx_category_sort', 'categories', ['sort_order'], unique=False)
    op.create_index(op.f('ix_categories_code'), 'categories', ['code'], unique=True)
    op.create_index(op.f('ix_categories_sort_order'), 'categories', ['sort_order'], unique=False)
    op.create_table('post_types',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_posttype_code', 'post_types', ['code'], unique=True)
    op.create_index(op.f('ix_post_types_code'), 'post_types', ['code'], unique=True)
    op.create_table('schools',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('province', sa.String(length=50), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('center_lat', sa.Float(), nullable=True),
    sa.Column('center_lng', sa.Float(), nullable=True),
    sa.Column('map_zoom', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_school_active', 'schools', ['is_active'], unique=False)
    op.create_index(op.f('ix_schools_code'), 'schools', ['code'], unique=True)
    op.create_table('tags',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('slug', sa.String(length=60), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('is_official', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tag_name', 'tags', ['name'], unique=True)
    op.create_index('idx_tag_official', 'tags', ['is_official'], unique=False)
    op.create_index('idx_tag_slug', 'tags', ['slug'], unique=True)
    op.create_index('idx_tag_usage', 'tags', ['usage_count'], unique=False)
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=True)
    op.create_index(op.f('ix_tags_slug'), 'tags', ['slug'], unique=True)
    op.create_table('locations',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('school_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('floor', sa.String(length=10), nullable=True),
    sa.Column('building', sa.String(length=100), nullable=True),
    sa.Column('post_count', sa.Integer(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_location_coords', 'locations', ['latitude', 'longitude'], unique=False)
    op.create_index('idx_location_school', 'locations', ['school_id'], unique=False)
    op.create_index('idx_location_school_name', 'locations', ['school_id', 'name'], unique=False)
    op.create_index('idx_location_verified', 'locations', ['is_verified'], unique=False)
    op.create_index(op.f('ix_locations_school_id'), 'locations', ['school_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('nickname', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('school_id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('bio', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_created', 'users', ['created_at'], unique=False)
    op.create_index('idx_user_role', 'users', ['role'], unique=False)
    op.create_index('idx_user_school', 'users', ['school_id'], unique=False)
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_school_id'), 'users', ['school_id'], unique=False)
    op.create_table('admin_operation_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('admin_id', sa.BigInteger(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('target_id', sa.BigInteger(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_adminlog_action', 'admin_operation_logs', ['action'], unique=False)
    op.create_index('idx_adminlog_admin', 'admin_operation_logs', ['admin_id', 'created_at'], unique=False)
    op.create_index('idx_adminlog_created', 'admin_operation_logs', ['created_at'], unique=False)
    op.create_index('idx_adminlog_target', 'admin_operation_logs', ['target_type', 'target_id'], unique=False)
    op.create_index(op.f('ix_admin_operation_logs_action'), 'admin_operation_logs', ['action'], unique=False)
    op.create_index(op.f('ix_admin_operation_logs_admin_id'), 'admin_operation_logs', ['admin_id'], unique=False)
    op.create_index(op.f('ix_admin_operation_logs_created_at'), 'admin_operation_logs', ['created_at'], unique=False)
    op.create_table('drafts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('category_id', sa.BigInteger(), nullable=True),
    sa.Column('post_type_id', sa.BigInteger(), nullable=True),
    sa.Column('location_id', sa.BigInteger(), nullable=True),
    sa.Column('is_anonymous', sa.Boolean(), nullable=False),
    sa.Column('extra_data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['post_type_id'], ['post_types.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_draft_user', 'drafts', ['user_id', 'updated_at'], unique=False)
    op.create_index(op.f('ix_drafts_user_id'), 'drafts', ['user_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.String(length=500), nullable=True),
    sa.Column('target_type', sa.String(length=50), nullable=True),
    sa.Column('target_id', sa.BigInteger(), nullable=True),
    sa.Column('actor_id', sa.BigInteger(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notification_target', 'notifications', ['target_type', 'target_id'], unique=False)
    op.create_index('idx_notification_user_read', 'notifications', ['user_id', 'is_read', 'created_at'], unique=False)
    op.create_index('idx_notification_user_type', 'notifications', ['user_id', 'type'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('posts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('school_id', sa.BigInteger(), nullable=False),
    sa.Column('category_id', sa.BigInteger(), nullable=False),
    sa.Column('post_type_id', sa.BigInteger(), nullable=False),
    sa.Column('location_id', sa.BigInteger(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_anonymous', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('like_count', sa.Integer(), nullable=False),
    sa.Column('comment_count', sa.Integer(), nullable=False),
    sa.Column('favorite_count', sa.Integer(), nullable=False),
    sa.Column('valid_count', sa.Integer(), nullable=False),
    sa.Column('invalid_count', sa.Integer(), nullable=False),
    sa.Column('expire_at', sa.DateTime(), nullable=True),
    sa.Column('activity_start_at', sa.DateTime(), nullable=True),
    sa.Column('activity_end_at', sa.DateTime(), nullable=True),
    sa.Column('lost_type', sa.String(length=10), nullable=True),
    sa.Column('contact_info', sa.String(length=255), nullable=True),
    sa.Column('is_top', sa.Boolean(), nullable=False),
    sa.Column('is_recommend', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['post_type_id'], ['post_types.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_post_category', 'posts', ['category_id'], unique=False)
    op.create_index('idx_post_expire', 'posts', ['expire_at'], unique=False)
    op.create_index('idx_post_location', 'posts', ['location_id'], unique=False)
    op.create_index('idx_post_school_category', 'posts', ['school_id', 'category_id', 'status'], unique=False)
    op.create_index('idx_post_school_status', 'posts', ['school_id', 'status'], unique=False)
    op.create_index('idx_post_status_created', 'posts', ['status', 'created_at'], unique=False)
    op.create_index('idx_post_status_recommend', 'posts', ['status', 'is_recommend', 'created_at'], unique=False)
    op.create_index('idx_post_type', 'posts', ['post_type_id'], unique=False)
    op.create_index('idx_post_user', 'posts', ['user_id'], unique=False)
    op.create_index(op.f('ix_posts_category_id'), 'posts', ['category_id'], unique=False)
    op.create_index(op.f('ix_posts_created_at'), 'posts', ['created_at'], unique=False)
    op.create_index(op.f('ix_posts_expire_at'), 'posts', ['expire_at'], unique=False)
    op.create_index(op.f('ix_posts_location_id'), 'posts', ['location_id'], unique=False)
    op.create_index(op.f('ix_posts_post_type_id'), 'posts', ['post_type_id'], unique=False)
    op.create_index(op.f('ix_posts_school_id'), 'posts', ['school_id'], unique=False)
    op.create_index(op.f('ix_posts_status'), 'posts', ['status'], unique=False)
    op.create_index(op.f('ix_posts_user_id'), 'posts', ['user_id'], unique=False)
    op.create_table('search_histories',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('keyword', sa.String(length=200), nullable=False),
    sa.Column('result_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_search_keyword', 'search_histories', ['keyword'], unique=False)
    op.create_index('idx_search_user', 'search_histories', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_search_histories_user_id'), 'search_histories', ['user_id'], unique=False)
    op.create_table('topic_collections',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cover_url', sa.String(length=500), nullable=True),
    sa.Column('school_id', sa.BigInteger(), nullable=False),
    sa.Column('creator_id', sa.BigInteger(), nullable=False),
    sa.Column('post_count', sa.Integer(), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_topic_creator', 'topic_collections', ['creator_id'], unique=False)
    op.create_index('idx_topic_school', 'topic_collections', ['school_id', 'status'], unique=False)
    op.create_index('idx_topic_sort', 'topic_collections', ['sort_order'], unique=False)
    op.create_index(op.f('ix_topic_collections_creator_id'), 'topic_collections', ['creator_id'], unique=False)
    op.create_index(op.f('ix_topic_collections_school_id'), 'topic_collections', ['school_id'], unique=False)
    op.create_table('browse_histories',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('post_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_browse_post', 'browse_histories', ['post_id'], unique=False)
    op.create_index('idx_browse_user', 'browse_histories', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_browse_histories_post_id'), 'browse_histories', ['post_id'], unique=False)
    op.create_index(op.f('ix_browse_histories_user_id'), 'browse_histories', ['user_id'], unique=False)
    op.create_table('comments',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('parent_id', sa.BigInteger(), nullable=True),
    sa.Column('reply_to_user_id', sa.BigInteger(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('like_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['comments.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['reply_to_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_comment_parent', 'comments', ['parent_id'], unique=False)
    op.create_index('idx_comment_post', 'comments', ['post_id', 'created_at'], unique=False)
    op.create_index('idx_comment_status', 'comments', ['status'], unique=False)
    op.create_index('idx_comment_user', 'comments', ['user_id'], unique=False)
    op.create_index(op.f('ix_comments_parent_id'), 'comments', ['parent_id'], unique=False)
    op.create_index(op.f('ix_comments_post_id'), 'comments', ['post_id'], unique=False)
    op.create_index(op.f('ix_comments_status'), 'comments', ['status'], unique=False)
    op.create_index(op.f('ix_comments_user_id'), 'comments', ['user_id'], unique=False)
    op.create_table('favorites',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_favorite_post_user', 'favorites', ['post_id', 'user_id'], unique=True)
    op.create_index('idx_favorite_user', 'favorites', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_favorites_post_id'), 'favorites', ['post_id'], unique=False)
    op.create_index(op.f('ix_favorites_user_id'), 'favorites', ['user_id'], unique=False)
    op.create_table('likes',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_like_post_user', 'likes', ['post_id', 'user_id'], unique=True)
    op.create_index('idx_like_user', 'likes', ['user_id'], unique=False)
    op.create_index(op.f('ix_likes_post_id'), 'likes', ['post_id'], unique=False)
    op.create_index(op.f('ix_likes_user_id'), 'likes', ['user_id'], unique=False)
    op.create_table('post_images',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.BigInteger(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_postimage_post', 'post_images', ['post_id', 'sort_order'], unique=False)
    op.create_index(op.f('ix_post_images_post_id'), 'post_images', ['post_id'], unique=False)
    op.create_table('post_tags',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.BigInteger(), nullable=False),
    sa.Column('tag_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_posttag_post_tag', 'post_tags', ['post_id', 'tag_id'], unique=True)
    op.create_index('idx_posttag_tag', 'post_tags', ['tag_id'], unique=False)
    op.create_index(op.f('ix_post_tags_post_id'), 'post_tags', ['post_id'], unique=False)
    op.create_index(op.f('ix_post_tags_tag_id'), 'post_tags', ['tag_id'], unique=False)
    op.create_table('topic_collection_posts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('topic_collection_id', sa.BigInteger(), nullable=False),
    sa.Column('post_id', sa.BigInteger(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['topic_collection_id'], ['topic_collections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tcp_post', 'topic_collection_posts', ['post_id'], unique=False)
    op.create_index('idx_tcp_topic_post', 'topic_collection_posts', ['topic_collection_id', 'post_id'], unique=True)
    op.create_index(op.f('ix_topic_collection_posts_post_id'), 'topic_collection_posts', ['post_id'], unique=False)
    op.create_index(op.f('ix_topic_collection_posts_topic_collection_id'), 'topic_collection_posts', ['topic_collection_id'], unique=False)
    op.create_table('validation_records',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('validation_type', sa.String(length=10), nullable=False),
    sa.Column('comment', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_validation_post', 'validation_records', ['post_id', 'created_at'], unique=False)
    op.create_index('idx_validation_post_type', 'validation_records', ['post_id', 'validation_type'], unique=False)
    op.create_index('idx_validation_user', 'validation_records', ['user_id'], unique=False)
    op.create_index(op.f('ix_validation_records_post_id'), 'validation_records', ['post_id'], unique=False)
    op.create_index(op.f('ix_validation_records_user_id'), 'validation_records', ['user_id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.BigInteger(), nullable=True),
    sa.Column('comment_id', sa.BigInteger(), nullable=True),
    sa.Column('reporter_id', sa.BigInteger(), nullable=False),
    sa.Column('report_type', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('handler_id', sa.BigInteger(), nullable=True),
    sa.Column('handle_result', sa.Text(), nullable=True),
    sa.Column('handled_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], ),
    sa.ForeignKeyConstraint(['handler_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_report_handler', 'reports', ['handler_id'], unique=False)
    op.create_index('idx_report_post_reporter', 'reports', ['post_id', 'reporter_id'], unique=True)
    op.create_index('idx_report_status', 'reports', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_reports_comment_id'), 'reports', ['comment_id'], unique=False)
    op.create_index(op.f('ix_reports_handler_id'), 'reports', ['handler_id'], unique=False)
    op.create_index(op.f('ix_reports_post_id'), 'reports', ['post_id'], unique=False)
    op.create_index(op.f('ix_reports_reporter_id'), 'reports', ['reporter_id'], unique=False)
    op.create_index(op.f('ix_reports_status'), 'reports', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reports_status'), table_name='reports')
    op.drop_index(op.f('ix_reports_reporter_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_post_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_handler_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_comment_id'), table_name='reports')
    op.drop_index('idx_report_status', table_name='reports')
    op.drop_index('idx_report_post_reporter', table_name='reports')
    op.drop_index('idx_report_handler', table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_validation_records_user_id'), table_name='validation_records')
    op.drop_index(op.f('ix_validation_records_post_id'), table_name='validation_records')
    op.drop_index('idx_validation_user', table_name='validation_records')
    op.drop_index('idx_validation_post_type', table_name='validation_records')
    op.drop_index('idx_validation_post', table_name='validation_records')
    op.drop_table('validation_records')
    op.drop_index(op.f('ix_topic_collection_posts_topic_collection_id'), table_name='topic_collection_posts')
    op.drop_index(op.f('ix_topic_collection_posts_post_id'), table_name='topic_collection_posts')
    op.drop_index('idx_tcp_topic_post', table_name='topic_collection_posts')
    op.drop_index('idx_tcp_post', table_name='topic_collection_posts')
    op.drop_table('topic_collection_posts')
    op.drop_index(op.f('ix_post_tags_tag_id'), table_name='post_tags')
    op.drop_index(op.f('ix_post_tags_post_id'), table_name='post_tags')
    op.drop_index('idx_posttag_tag', table_name='post_tags')
    op.drop_index('idx_posttag_post_tag', table_name='post_tags')
    op.drop_table('post_tags')
    op.drop_index(op.f('ix_post_images_post_id'), table_name='post_images')
    op.drop_index('idx_postimage_post', table_name='post_images')
    op.drop_table('post_images')
    op.drop_index(op.f('ix_likes_user_id'), table_name='likes')
    op.drop_index(op.f('ix_likes_post_id'), table_name='likes')
    op.drop_index('idx_like_user', table_name='likes')
    op.drop_index('idx_like_post_user', table_name='likes')
    op.drop_table('likes')
    op.drop_index(op.f('ix_favorites_user_id'), table_name='favorites')
    op.drop_index(op.f('ix_favorites_post_id'), table_name='favorites')
    op.drop_index('idx_favorite_user', table_name='favorites')
    op.drop_index('idx_favorite_post_user', table_name='favorites')
    op.drop_table('favorites')
    op.drop_index(op.f('ix_comments_user_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_status'), table_name='comments')
    op.drop_index(op.f('ix_comments_post_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_parent_id'), table_name='comments')
    op.drop_index('idx_comment_user', table_name='comments')
    op.drop_index('idx_comment_status', table_name='comments')
    op.drop_index('idx_comment_post', table_name='comments')
    op.drop_index('idx_comment_parent', table_name='comments')
    op.drop_table('comments')
    op.drop_index(op.f('ix_browse_histories_user_id'), table_name='browse_histories')
    op.drop_index(op.f('ix_browse_histories_post_id'), table_name='browse_histories')
    op.drop_index('idx_browse_user', table_name='browse_histories')
    op.drop_index('idx_browse_post', table_name='browse_histories')
    op.drop_table('browse_histories')
    op.drop_index(op.f('ix_topic_collections_school_id'), table_name='topic_collections')
    op.drop_index(op.f('ix_topic_collections_creator_id'), table_name='topic_collections')
    op.drop_index('idx_topic_sort', table_name='topic_collections')
    op.drop_index('idx_topic_school', table_name='topic_collections')
    op.drop_index('idx_topic_creator', table_name='topic_collections')
    op.drop_table('topic_collections')
    op.drop_index(op.f('ix_search_histories_user_id'), table_name='search_histories')
    op.drop_index('idx_search_user', table_name='search_histories')
    op.drop_index('idx_search_keyword', table_name='search_histories')
    op.drop_table('search_histories')
    op.drop_index(op.f('ix_posts_user_id'), table_name='posts')
    op.drop_index(op.f('ix_posts_status'), table_name='posts')
    op.drop_index(op.f('ix_posts_school_id'), table_name='posts')
    op.drop_index(op.f('ix_posts_post_type_id'), table_name='posts')
    op.drop_index(op.f('ix_posts_location_id'), table_name='posts')
    op.drop_index(op.f('ix_posts_expire_at'), table_name='posts')
    op.drop_index(op.f('ix_posts_created_at'), table_name='posts')
    op.drop_index(op.f('ix_posts_category_id'), table_name='posts')
    op.drop_index('idx_post_user', table_name='posts')
    op.drop_index('idx_post_type', table_name='posts')
    op.drop_index('idx_post_status_recommend', table_name='posts')
    op.drop_index('idx_post_status_created', table_name='posts')
    op.drop_index('idx_post_school_status', table_name='posts')
    op.drop_index('idx_post_school_category', table_name='posts')
    op.drop_index('idx_post_location', table_name='posts')
    op.drop_index('idx_post_expire', table_name='posts')
    op.drop_index('idx_post_category', table_name='posts')
    op.drop_table('posts')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index('idx_notification_user_type', table_name='notifications')
    op.drop_index('idx_notification_user_read', table_name='notifications')
    op.drop_index('idx_notification_target', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_drafts_user_id'), table_name='drafts')
    op.drop_index('idx_draft_user', table_name='drafts')
    op.drop_table('drafts')
    op.drop_index(op.f('ix_admin_operation_logs_created_at'), table_name='admin_operation_logs')
    op.drop_index(op.f('ix_admin_operation_logs_admin_id'), table_name='admin_operation_logs')
    op.drop_index(op.f('ix_admin_operation_logs_action'), table_name='admin_operation_logs')
    op.drop_index('idx_adminlog_target', table_name='admin_operation_logs')
    op.drop_index('idx_adminlog_created', table_name='admin_operation_logs')
    op.drop_index('idx_adminlog_admin', table_name='admin_operation_logs')
    op.drop_index('idx_adminlog_action', table_name='admin_operation_logs')
    op.drop_table('admin_operation_logs')
    op.drop_index(op.f('ix_users_school_id'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_index('idx_user_school', table_name='users')
    op.drop_index('idx_user_role', table_name='users')
    op.drop_index('idx_user_created', table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_locations_school_id'), table_name='locations')
    op.drop_index('idx_location_verified', table_name='locations')
    op.drop_index('idx_location_school_name', table_name='locations')
    op.drop_index('idx_location_school', table_name='locations')
    op.drop_index('idx_location_coords', table_name='locations')
    op.drop_table('locations')
    op.drop_index(op.f('ix_tags_slug'), table_name='tags')
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.drop_index('idx_tag_usage', table_name='tags')
    op.drop_index('idx_tag_slug', table_name='tags')
    op.drop_index('idx_tag_official', table_name='tags')
    op.drop_index('idx_tag_name', table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_schools_code'), table_name='schools')
    op.drop_index('idx_school_active', table_name='schools')
    op.drop_table('schools')
    op.drop_index(op.f('ix_post_types_code'), table_name='post_types')
    op.drop_index('idx_posttype_code', table_name='post_types')
    op.drop_table('post_types')
    op.drop_index(op.f('ix_categories_sort_order'), table_name='categories')
    op.drop_index(op.f('ix_categories_code'), table_name='categories')
    op.drop_index('idx_category_sort', table_name='categories')
    op.drop_index('idx_category_code', table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
